namespace GatherGrove.Application.DTOs;

/// <summary>
/// Response for member segment operations
/// </summary>
public class MemberSegmentResponse
{
    /// <summary>
    /// Unique identifier for the segment
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Club this segment belongs to
    /// </summary>
    public int ClubId { get; set; }

    /// <summary>
    /// Name of the segment
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Description of the segment
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Filter criteria as a structured object
    /// </summary>
    public SegmentFilterCriteria FilterCriteria { get; set; } = new();

    /// <summary>
    /// Raw filter criteria JSON for storage
    /// </summary>
    public string FilterCriteriaJson { get; set; } = string.Empty;

    /// <summary>
    /// Whether the segment is active
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Whether this segment was generated by the system
    /// </summary>
    public bool IsSystemGenerated { get; set; }

    /// <summary>
    /// Current count of members in this segment
    /// </summary>
    public int MemberCount { get; set; }

    /// <summary>
    /// When the segment was last calculated
    /// </summary>
    public DateTime? LastCalculated { get; set; }

    /// <summary>
    /// Duration of last calculation in milliseconds
    /// </summary>
    public int? CalculationDurationMs { get; set; }

    /// <summary>
    /// When the segment was created
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created the segment
    /// </summary>
    public string CreatedByUserName { get; set; } = string.Empty;

    /// <summary>
    /// When the segment was last updated
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Performance metrics for this segment (if requested)
    /// </summary>
    public SegmentPerformanceMetrics? PerformanceMetrics { get; set; }
}

/// <summary>
/// Response for segment calculation operations
/// </summary>
public class SegmentCalculationResult
{
    /// <summary>
    /// ID of the segment that was calculated
    /// </summary>
    public int SegmentId { get; set; }

    /// <summary>
    /// Number of members in the segment after calculation
    /// </summary>
    public int MemberCount { get; set; }

    /// <summary>
    /// Duration of the calculation in milliseconds
    /// </summary>
    public int CalculationDurationMs { get; set; }

    /// <summary>
    /// When the calculation was performed
    /// </summary>
    public DateTime CalculatedAt { get; set; }

    /// <summary>
    /// Whether the segment cache was updated
    /// </summary>
    public bool CacheUpdated { get; set; }

    /// <summary>
    /// Changes in member count since last calculation
    /// </summary>
    public int MemberCountChange { get; set; }

    /// <summary>
    /// List of members added to the segment
    /// </summary>
    public List<SegmentMemberChange> MembersAdded { get; set; } = new();

    /// <summary>
    /// List of members removed from the segment
    /// </summary>
    public List<SegmentMemberChange> MembersRemoved { get; set; } = new();
}

/// <summary>
/// Response for getting segment members
/// </summary>
public class SegmentMembersResult
{
    /// <summary>
    /// Total number of members in the segment
    /// </summary>
    public int TotalCount { get; set; }

    /// <summary>
    /// Current page number
    /// </summary>
    public int CurrentPage { get; set; }

    /// <summary>
    /// Number of results per page
    /// </summary>
    public int PageSize { get; set; }

    /// <summary>
    /// Total number of pages
    /// </summary>
    public int TotalPages => (int)Math.Ceiling((double)TotalCount / PageSize);

    /// <summary>
    /// List of members in the segment
    /// </summary>
    public List<SegmentMemberDetail> Members { get; set; } = new();

    /// <summary>
    /// When the segment was last calculated
    /// </summary>
    public DateTime? LastCalculated { get; set; }

    /// <summary>
    /// Whether the cache is up to date
    /// </summary>
    public bool CacheIsValid { get; set; }
}

/// <summary>
/// Detailed member information for segment results
/// </summary>
public class SegmentMemberDetail
{
    /// <summary>
    /// Member ID
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// Member full name
    /// </summary>
    public string MemberName { get; set; } = string.Empty;

    /// <summary>
    /// Member email
    /// </summary>
    public string MemberEmail { get; set; } = string.Empty;

    /// <summary>
    /// Member status
    /// </summary>
    public string MemberStatus { get; set; } = string.Empty;

    /// <summary>
    /// When the member joined
    /// </summary>
    public DateTime JoinDate { get; set; }

    /// <summary>
    /// When the member was last active
    /// </summary>
    public DateTime? LastActive { get; set; }

    /// <summary>
    /// When this member was added to the segment cache
    /// </summary>
    public DateTime AddedToSegmentAt { get; set; }

    /// <summary>
    /// Engagement data (if requested)
    /// </summary>
    public MemberEngagementData? EngagementData { get; set; }

    /// <summary>
    /// Custom field values (if requested)
    /// </summary>
    public Dictionary<string, object?> CustomFields { get; set; } = new();

    /// <summary>
    /// Member tags (if requested)
    /// </summary>
    public List<TagAssignmentResponse> Tags { get; set; } = new();
}

/// <summary>
/// Member engagement data for segment results
/// </summary>
public class MemberEngagementData
{
    /// <summary>
    /// Overall engagement score
    /// </summary>
    public decimal OverallScore { get; set; }

    /// <summary>
    /// Engagement level (1=High, 2=Moderate, 3=At Risk)
    /// </summary>
    public int Level { get; set; }

    /// <summary>
    /// Visual indicator color
    /// </summary>
    public string VisualIndicator { get; set; } = string.Empty;

    /// <summary>
    /// Individual score components
    /// </summary>
    public EngagementScoreComponents ScoreComponents { get; set; } = new();
}

/// <summary>
/// Individual engagement score components
/// </summary>
public class EngagementScoreComponents
{
    public decimal LoginFrequencyScore { get; set; }
    public decimal EventParticipationScore { get; set; }
    public decimal CommunicationScore { get; set; }
    public decimal FeatureUsageScore { get; set; }
    public decimal ProfileCompletenessScore { get; set; }
}

/// <summary>
/// Represents a change in segment membership
/// </summary>
public class SegmentMemberChange
{
    /// <summary>
    /// Member ID
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// Member name for reference
    /// </summary>
    public string MemberName { get; set; } = string.Empty;

    /// <summary>
    /// Reason for the change
    /// </summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>
    /// When the change occurred
    /// </summary>
    public DateTime ChangedAt { get; set; }
}

/// <summary>
/// Performance metrics for a segment
/// </summary>
public class SegmentPerformanceMetrics
{
    /// <summary>
    /// Average calculation time in milliseconds
    /// </summary>
    public double AverageCalculationTime { get; set; }

    /// <summary>
    /// Number of times the segment has been calculated
    /// </summary>
    public int CalculationCount { get; set; }

    /// <summary>
    /// Cache hit ratio for segment queries
    /// </summary>
    public decimal CacheHitRatio { get; set; }

    /// <summary>
    /// Trend in member count over time
    /// </summary>
    public List<MemberCountTrend> MemberCountTrends { get; set; } = new();
}

/// <summary>
/// Member count trend data point
/// </summary>
public class MemberCountTrend
{
    /// <summary>
    /// Date of the trend point
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Member count at that date
    /// </summary>
    public int MemberCount { get; set; }
}

/// <summary>
/// Result of filter execution
/// </summary>
public class FilterExecutionResult
{
    /// <summary>
    /// Total number of matching members
    /// </summary>
    public int TotalCount { get; set; }

    /// <summary>
    /// List of matching members
    /// </summary>
    public List<SegmentMemberDetail> Members { get; set; } = new();

    /// <summary>
    /// Execution time in milliseconds
    /// </summary>
    public int ExecutionTimeMs { get; set; }

    /// <summary>
    /// Filter criteria that was executed
    /// </summary>
    public SegmentFilterCriteria ExecutedCriteria { get; set; } = new();
}

/// <summary>
/// Response for filter template operations
/// </summary>
public class FilterTemplateResponse
{
    /// <summary>
    /// Template ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Template name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Template description
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Template category
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Filter criteria
    /// </summary>
    public SegmentFilterCriteria FilterCriteria { get; set; } = new();

    /// <summary>
    /// Whether this is a system template
    /// </summary>
    public bool IsSystemTemplate { get; set; }

    /// <summary>
    /// Whether the template is active
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// How many times this template has been used
    /// </summary>
    public int UsageCount { get; set; }

    /// <summary>
    /// When the template was created
    /// </summary>
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// Result of cache refresh operation
/// </summary>
public class CacheRefreshResult
{
    /// <summary>
    /// Number of segments processed
    /// </summary>
    public int ProcessedSegments { get; set; }

    /// <summary>
    /// Number of successful refreshes
    /// </summary>
    public int SuccessfulRefreshes { get; set; }

    /// <summary>
    /// Number of failed refreshes
    /// </summary>
    public int FailedRefreshes { get; set; }

    /// <summary>
    /// Total duration of refresh operation
    /// </summary>
    public int TotalDurationMs { get; set; }

    /// <summary>
    /// List of errors that occurred
    /// </summary>
    public List<string> Errors { get; set; } = new();

    /// <summary>
    /// When the refresh was performed
    /// </summary>
    public DateTime RefreshedAt { get; set; }
}

/// <summary>
/// Result of filter criteria validation
/// </summary>
public class FilterValidationResult
{
    /// <summary>
    /// Whether the criteria is valid
    /// </summary>
    public bool IsValid { get; set; }

    /// <summary>
    /// List of validation errors
    /// </summary>
    public List<string> Errors { get; set; } = new();

    /// <summary>
    /// List of validation warnings
    /// </summary>
    public List<string> Warnings { get; set; } = new();

    /// <summary>
    /// Estimated number of members that would match
    /// </summary>
    public int EstimatedMemberCount { get; set; }

    /// <summary>
    /// Estimated execution time in milliseconds
    /// </summary>
    public int EstimatedExecutionTimeMs { get; set; }

    /// <summary>
    /// Performance impact level
    /// </summary>
    public PerformanceImpact PerformanceImpact { get; set; }
}

/// <summary>
/// Performance impact levels
/// </summary>
public enum PerformanceImpact
{
    Low,
    Medium,
    High,
    VeryHigh
}