using System.ComponentModel.DataAnnotations;

namespace GatherGrove.Application.DTOs;

/// <summary>
/// Request model for upgrading a club's subscription to a higher tier or different billing cycle
/// </summary>
public class UpgradeSubscriptionRequest
{
    /// <summary>
    /// The Stripe price ID for the subscription plan (e.g., "price_grow_monthly", "price_unlimited_annual")
    /// </summary>
    [Required(ErrorMessage = "Plan ID is required")]
    public string PlanId { get; set; } = string.Empty;

    /// <summary>
    /// The Stripe payment method ID generated by Stripe Elements on the frontend
    /// </summary>
    [Required(ErrorMessage = "Payment method ID is required")]
    public string PaymentMethodId { get; set; } = string.Empty;

    /// <summary>
    /// The target tier name (Seed, Grow, or Expand)
    /// </summary>
    [Required(ErrorMessage = "Target tier is required")]
    [RegularExpression("^(Seed|Grow|Expand|Unlimited)$", ErrorMessage = "TargetTier must be 'Seed', 'Grow', or 'Expand'")]
    public string TargetTier { get; set; } = string.Empty;

    /// <summary>
    /// The billing cycle (monthly or annual)
    /// </summary>
    [Required(ErrorMessage = "Billing cycle is required")]
    [RegularExpression("^(monthly|annual)$", ErrorMessage = "BillingCycle must be 'monthly' or 'annual'")]
    public string BillingCycle { get; set; } = string.Empty;

    /// <summary>
    /// Optional promo code to apply to the subscription
    /// </summary>
    public string? PromoCode { get; set; }
}
