using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GatherGrove.Domain.Entities;

/// <summary>
/// Represents a dynamic segment of members based on criteria
/// </summary>
[Table("MemberSegments")]
public class MemberSegment
{
    /// <summary>
    /// Unique identifier for the segment
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// The club this segment belongs to
    /// </summary>
    [Required]
    public int ClubId { get; set; }

    /// <summary>
    /// The name of the segment
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Optional description of the segment
    /// </summary>
    [StringLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Filter criteria as JSON string for flexibility
    /// </summary>
    [Required]
    [Column(TypeName = "ntext")]
    public string FilterCriteria { get; set; } = "{}";

    /// <summary>
    /// Whether the segment is active
    /// </summary>
    [Required]
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Whether this segment was generated by the system
    /// </summary>
    [Required]
    public bool IsSystemGenerated { get; set; } = false;

    /// <summary>
    /// Cached count of members in this segment
    /// </summary>
    [Required]
    public int MemberCount { get; set; } = 0;

    /// <summary>
    /// When the segment was last calculated
    /// </summary>
    public DateTime? LastCalculated { get; set; }

    /// <summary>
    /// How long the last calculation took in milliseconds
    /// </summary>
    public int? CalculationDurationMs { get; set; }

    /// <summary>
    /// When this segment was created
    /// </summary>
    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// User who created this segment
    /// </summary>
    [Required]
    public int CreatedByUserId { get; set; }

    /// <summary>
    /// When this segment was last updated
    /// </summary>
    [Required]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    [ForeignKey(nameof(ClubId))]
    public virtual Club Club { get; set; } = null!;

    [ForeignKey(nameof(CreatedByUserId))]
    public virtual User CreatedByUser { get; set; } = null!;

    /// <summary>
    /// Collection of cached member assignments for this segment
    /// </summary>
    public virtual ICollection<MemberSegmentCache> CachedMembers { get; set; } = new List<MemberSegmentCache>();

    /// <summary>
    /// Collection of history records for this segment
    /// </summary>
    public virtual ICollection<MemberSegmentHistory> History { get; set; } = new List<MemberSegmentHistory>();
}