/**
 * Design Token Build Pipeline
 *
 * Reads canonical token JSON files from shared/design-tokens/ and generates
 * platform-specific output files:
 *
 *   client/src/generated/tokens.css   — CSS custom properties (:root + .light)
 *   client/src/generated/tokens.ts    — Typed TypeScript constants (HSL for web)
 *   mobile/src/generated/tokens.ts    — Typed TypeScript constants (hex, px for mobile)
 *   backend/src/.../Generated/DesignTokens.cs — C# static class (hex constants)
 *
 * Run: node shared/design-tokens/build.mjs
 * Watch: node --watch shared/design-tokens/build.mjs
 */

import { readFile, writeFile, mkdir } from'node:fs/promises';
import { existsSync } from'node:fs';
import path from'node:path';
import { fileURLToPath } from'node:url';

import { hexToHsl } from'./transforms/css-hsl.mjs';
import { abstractShadowToRN } from'./transforms/rn-shadow.mjs';
import { generateCSharpFile } from'./transforms/csharp.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname,'../..');
const TOKENS_DIR = __dirname;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

async function readJson(filename) {
  const filepath = path.join(TOKENS_DIR, filename);
  const raw = await readFile(filepath,'utf-8');
  return JSON.parse(raw);
}

async function ensureDir(dir) {
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

async function writeOutput(filepath, content) {
  await ensureDir(path.dirname(filepath));
  await writeFile(filepath, content,'utf-8');
  const rel = path.relative(ROOT, filepath);
  console.log(`  ✓ ${rel}`);
}

const HEADER = `/* auto-generated by shared/design-tokens/build.mjs — do not edit manually */\n/* Source: shared/design-tokens/ — run'npm run tokens:build' to regenerate */\n\n`;
const TS_HEADER = `// auto-generated by shared/design-tokens/build.mjs — do not edit manually\n// Source: shared/design-tokens/ — run'npm run tokens:build' to regenerate\n\n`;

// ─────────────────────────────────────────────────────────────────────────────
// Load all token files
// ─────────────────────────────────────────────────────────────────────────────

async function loadTokens() {
  const [colors, spacing, typography, shadows, radius, breakpoints, zIndex, animation, accessibility] =
    await Promise.all([
      readJson('colors.json'),
      readJson('spacing.json'),
      readJson('typography.json'),
      readJson('shadows.json'),
      readJson('radius.json'),
      readJson('breakpoints.json'),
      readJson('z-index.json'),
      readJson('animation.json'),
      readJson('accessibility.json'),
    ]);

  return { colors, spacing, typography, shadows, radius, breakpoints, zIndex, animation, accessibility };
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform 1: CSS (client/src/generated/tokens.css)
// ─────────────────────────────────────────────────────────────────────────────

function buildCss(tokens) {
  const { colors, spacing, typography, shadows, radius, accessibility } = tokens;

  const lines = [HEADER];

  // ── :root block ────────────────────────────────────────────────────────────
  lines.push(':root {');
  lines.push('  /* ── Border Radius ────────────────────────────────────── */');
  lines.push(`  --radius:      ${radius.radius.DEFAULT.value};`);
  lines.push(`  --radius-sm:   ${radius.radius.sm.value};`);
  lines.push(`  --radius-md:   ${radius.radius.md.value};`);
  lines.push(`  --radius-lg:   ${radius.radius.lg.value};`);
  lines.push(`  --radius-xl:   ${radius.radius.xl.value};`);
  lines.push(`  --radius-2xl:  ${radius.radius['2xl'].value};`);
  lines.push(`  --radius-full: ${radius.radius.full.value};`);
  lines.push('');
  lines.push('  /* ── Spacing ──────────────────────────────────────────── */');
  lines.push(`  --section-padding:    ${spacing.layout['section-padding'].value};`);
  lines.push(`  --section-padding-sm: ${spacing.layout['section-padding-sm'].value};`);
  lines.push(`  --container-padding:  ${spacing.layout['container-padding'].value};`);
  lines.push(`  --grid-gap:           ${spacing.layout['grid-gap'].value};`);
  lines.push(`  --grid-gap-sm:        ${spacing.layout['grid-gap-sm'].value};`);
  lines.push(`  --grid-gap-lg:        ${spacing.layout['grid-gap-lg'].value};`);
  lines.push('');
  lines.push('  /* ── Typography Scale ─────────────────────────────────── */');
  for (const [key, token] of Object.entries(typography.typography.fontSize)) {
    lines.push(`  --text-${key}: ${token.value};`);
  }
  lines.push('');
  lines.push('  /* ── Shadows ──────────────────────────────────────────── */');
  const shadowCssVars = ['xs','sm','md','lg','xl','2xl','inner','soft','medium','strong','colored'];
  for (const key of shadowCssVars) {
    if (shadows.shadow[key]?.css) {
      lines.push(`  --shadow-${key}: ${shadows.shadow[key].css};`);
    }
  }
  lines.push('');
  lines.push('  /* ── Accessibility ────────────────────────────────────── */');
  lines.push(`  --focus-ring-width:  ${accessibility.accessibility.focusRing.width.value};`);
  lines.push(`  --focus-ring-offset: ${accessibility.accessibility.focusRing.offset.value};`);
  lines.push(`  --focus-ring-color:  hsl(var(--ring));`);
  lines.push(`  --min-touch-target:  ${accessibility.accessibility.touchTarget.minimum.value};`);
  lines.push('');
  lines.push('  /* ── Light theme — GatherGrove brand colors ───────────── */');
  for (const [varName, hslTriplet] of Object.entries(colors.cssVars.light)) {
    if (varName.startsWith('--')) {
      lines.push(`  ${varName}: ${hslTriplet};`);
    }
  }
  lines.push('}');
  lines.push('');

  // ── .light block ────────────────────────────────────────────────────────────
  lines.push('.light {');
  for (const [varName, hslTriplet] of Object.entries(colors.cssVars.light)) {
    if (varName.startsWith('--')) {
      lines.push(`  ${varName}: ${hslTriplet};`);
    }
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform 2: TypeScript Web (client/src/generated/tokens.ts)
// ─────────────────────────────────────────────────────────────────────────────

function buildTsWeb(tokens) {
  const { colors, spacing, typography, shadows, radius, breakpoints, zIndex, animation, accessibility } = tokens;

  const lines = [TS_HEADER];

  // Color tokens (HSL triplets for CSS vars integration)
  const colorObj = {};

  // Brand colors (hex → HSL)
  colorObj.brand = {};
  for (const [paletteName, palette] of Object.entries(colors.brand)) {
    colorObj.brand[paletteName] = {};
    for (const [step, token] of Object.entries(palette)) {
      colorObj.brand[paletteName][step] = hexToHsl(token.value);
    }
  }

  // Semantic colors
  colorObj.semantic = {};
  for (const [name, palette] of Object.entries(colors.semantic)) {
    colorObj.semantic[name] = {};
    for (const [step, token] of Object.entries(palette)) {
      colorObj.semantic[name][step] = hexToHsl(token.value);
    }
  }

  // Neutral
  colorObj.neutral = {};
  for (const [step, token] of Object.entries(colors.neutral)) {
    colorObj.neutral[step] = hexToHsl(token.value);
  }

  // Chart
  colorObj.chart = {
    palette: {},
    positive: hexToHsl(colors.chart.positive.value),
    negative: hexToHsl(colors.chart.negative.value),
    neutral: hexToHsl(colors.chart.neutral.value),
  };
  for (const [n, token] of Object.entries(colors.chart.palette)) {
    colorObj.chart.palette[n] = hexToHsl(token.value);
  }

  // CSS var theme values (HSL triplets, direct copy)
  colorObj.cssVars = {
    light: { ...colors.cssVars.light },
  };

  // Spacing
  const spacingObj = {};
  for (const [k, v] of Object.entries(spacing.spacing)) {
    spacingObj[k] = v.value;
  }

  // Layout spacing
  const layoutObj = {};
  for (const [k, v] of Object.entries(spacing.layout)) {
    layoutObj[k] = v.value;
  }

  // Typography
  const typographyObj = {
    fontSize: {},
    fontWeight: {},
    lineHeight: {},
    fontFamily: {},
  };
  for (const [k, v] of Object.entries(typography.typography.fontSize)) {
    typographyObj.fontSize[k] = v.value;
  }
  for (const [k, v] of Object.entries(typography.typography.fontWeight)) {
    typographyObj.fontWeight[k] = v.value;
  }
  for (const [k, v] of Object.entries(typography.typography.lineHeight)) {
    typographyObj.lineHeight[k] = v.value;
  }
  for (const [k, v] of Object.entries(typography.typography.fontFamily)) {
    typographyObj.fontFamily[k] = v.value;
  }

  // Shadows (CSS string values)
  const shadowObj = {};
  for (const [k, v] of Object.entries(shadows.shadow)) {
    shadowObj[k] = v.css ??'0 0 #0000';
  }

  // Radius
  const radiusObj = {};
  for (const [k, v] of Object.entries(radius.radius)) {
    radiusObj[k] = v.value;
  }

  // Breakpoints
  const breakpointObj = {};
  for (const [k, v] of Object.entries(breakpoints.breakpoint)) {
    breakpointObj[k] = v.value;
  }

  // Z-index
  const zIndexObj = {};
  for (const [k, v] of Object.entries(zIndex.zIndex)) {
    zIndexObj[k] = v.value;
  }

  // Animation
  const animationObj = { duration: {}, easing: {} };
  for (const [k, v] of Object.entries(animation.animation.duration)) {
    animationObj.duration[k] = v.value;
  }
  for (const [k, v] of Object.entries(animation.animation.easing)) {
    animationObj.easing[k] = v.value;
  }

  // Accessibility
  const a11yObj = {
    touchTarget: {
      minimum: accessibility.accessibility.touchTarget.minimum.value,
      recommended: accessibility.accessibility.touchTarget.recommended.value,
      optimal: accessibility.accessibility.touchTarget.optimal.value,
      spacing: accessibility.accessibility.touchTarget.spacing.value,
    },
    focusRing: {
      width: accessibility.accessibility.focusRing.width.value,
      offset: accessibility.accessibility.focusRing.offset.value,
    },
  };

  const tokensObj = {
    color: colorObj,
    spacing: spacingObj,
    layout: layoutObj,
    typography: typographyObj,
    shadow: shadowObj,
    radius: radiusObj,
    breakpoint: breakpointObj,
    zIndex: zIndexObj,
    animation: animationObj,
    accessibility: a11yObj,
  };

  lines.push(`export const tokens = ${JSON.stringify(tokensObj, null, 2)} as const;\n`);
  lines.push('export type Tokens = typeof tokens;');
  lines.push('export type ColorTokens = typeof tokens.color;');
  lines.push('export type SpacingTokens = typeof tokens.spacing;');
  lines.push('');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform 3: TypeScript Mobile (mobile/src/generated/tokens.ts)
// ─────────────────────────────────────────────────────────────────────────────

function buildTsMobile(tokens) {
  const { colors, spacing, shadows, radius, breakpoints, zIndex, animation, accessibility } = tokens;

  const lines = [TS_HEADER];

  // Color tokens (hex values, as used in React Native StyleSheet)
  const colorObj = {};
  for (const [paletteName, palette] of Object.entries(colors.brand)) {
    colorObj[paletteName.toUpperCase() +'_COLORS'] = {};
    for (const [step, token] of Object.entries(palette)) {
      colorObj[paletteName.toUpperCase() +'_COLORS'][step] = token.value;
    }
  }

  colorObj.NEUTRAL_COLORS = {};
  for (const [step, token] of Object.entries(colors.neutral)) {
    colorObj.NEUTRAL_COLORS[step] = token.value;
  }

  colorObj.SEMANTIC_COLORS = {};
  for (const [name, palette] of Object.entries(colors.semantic)) {
    colorObj.SEMANTIC_COLORS[name] = {};
    for (const [step, token] of Object.entries(palette)) {
      colorObj.SEMANTIC_COLORS[name][step] = token.value;
    }
  }

  colorObj.SPECIAL_COLORS = {
    star: colors.special.star.value,
    link: colors.special.link.light.value,
    socialAuth: {
      google: colors.special.socialAuth.google.value,
      apple: colors.special.socialAuth.apple.value,
      microsoft: colors.special.socialAuth.microsoft.value,
    },
  };

  // Spacing (numeric px)
  const spacingObj = {};
  for (const [k, v] of Object.entries(spacing.spacing)) {
    spacingObj[k] = v.mobile;
  }

  // Radius (numeric px)
  const radiusObj = {};
  for (const [k, v] of Object.entries(radius.radius)) {
    radiusObj[k] = v.mobile;
  }

  // Breakpoints (numeric px, mobile values)
  const breakpointObj = {};
  for (const [k, v] of Object.entries(breakpoints.breakpoint)) {
    breakpointObj[k] = v.mobile;
  }

  // Z-index (numeric)
  const zIndexObj = {};
  for (const [k, v] of Object.entries(zIndex.zIndex)) {
    zIndexObj[k] = v.value;
  }

  // Animation durations (numeric ms)
  const animationObj = { duration: {}, easing: {} };
  for (const [k, v] of Object.entries(animation.animation.duration)) {
    animationObj.duration[k] = v.ms;
  }
  for (const [k, v] of Object.entries(animation.animation.easing)) {
    animationObj.easing[k] = v.value;
  }

  // Shadows (React Native shadow objects)
  const shadowObj = {};
  for (const [k, v] of Object.entries(shadows.shadow)) {
    shadowObj[k] = abstractShadowToRN(v.value);
  }

  // Accessibility (numeric px)
  const a11yObj = {
    touchTarget: {
      minimum: accessibility.accessibility.touchTarget.minimum.mobile,
      recommended: accessibility.accessibility.touchTarget.recommended.mobile,
      optimal: accessibility.accessibility.touchTarget.optimal.mobile,
      spacing: accessibility.accessibility.touchTarget.spacing.mobile,
    },
    focusRing: {
      width: parseInt(accessibility.accessibility.focusRing.width.value),
      offset: parseInt(accessibility.accessibility.focusRing.offset.value),
    },
  };

  const tokensObj = {
    colors: colorObj,
    spacing: spacingObj,
    radius: radiusObj,
    breakpoints: breakpointObj,
    zIndex: zIndexObj,
    animation: animationObj,
    shadow: shadowObj,
    accessibility: a11yObj,
  };

  lines.push(`export const tokens = ${JSON.stringify(tokensObj, null, 2)} as const;\n`);
  lines.push('export type MobileTokens = typeof tokens;');
  lines.push('export type MobileColorTokens = typeof tokens.colors;');
  lines.push('');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform 4: C# (backend/src/GatherGrove.Application/Generated/DesignTokens.cs)
// ─────────────────────────────────────────────────────────────────────────────

function buildCSharp(tokens) {
  const { colors } = tokens;

  // Collect flat map of name → hex value for important brand/semantic colors
  const colorMap = {};

  // Brand primary
  for (const [step, token] of Object.entries(colors.brand.primary)) {
    colorMap[`brand.primary.${step}`] = token.value;
  }

  // Brand secondary
  for (const [step, token] of Object.entries(colors.brand.secondary)) {
    colorMap[`brand.secondary.${step}`] = token.value;
  }

  // Brand accent
  for (const [step, token] of Object.entries(colors.brand.accent)) {
    colorMap[`brand.accent.${step}`] = token.value;
  }

  // Neutral
  for (const [step, token] of Object.entries(colors.neutral)) {
    colorMap[`neutral.${step}`] = token.value;
  }

  // Semantic (light/dark + 50-900)
  for (const [name, palette] of Object.entries(colors.semantic)) {
    for (const [step, token] of Object.entries(palette)) {
      colorMap[`semantic.${name}.${step}`] = token.value;
    }
  }

  // Chart
  for (const [n, token] of Object.entries(colors.chart.palette)) {
    colorMap[`chart.palette.${n}`] = token.value;
  }
  colorMap['chart.positive'] = colors.chart.positive.value;
  colorMap['chart.negative'] = colors.chart.negative.value;
  colorMap['chart.neutral'] = colors.chart.neutral.value;

  // Special
  colorMap['special.star'] = colors.special.star.value;
  colorMap['special.link.light'] = colors.special.link.light.value;
  colorMap['special.link.light'] = colors.special.link.light.value;
  colorMap['special.socialAuth.google'] = colors.special.socialAuth.google.value;
  colorMap['special.socialAuth.apple'] = colors.special.socialAuth.apple.value;
  colorMap['special.socialAuth.microsoft'] = colors.special.socialAuth.microsoft.value;

  return generateCSharpFile({ colors: colorMap });
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Patch globals.css with generated token vars (between markers)
// ─────────────────────────────────────────────────────────────────────────────

const GLOBALS_BEGIN ='/* ── BEGIN AUTO-GENERATED TOKENS (shared/design-tokens/build.mjs) ── */';
const GLOBALS_END   ='/* ── END AUTO-GENERATED TOKENS ── */';

async function patchGlobalsCss(cssVarBlock) {
  const globalsPath = path.join(ROOT,'client/src/app/globals.css');
  const original = await readFile(globalsPath,'utf-8');

  // Strip the generated comment header from the standalone tokens.css content
  // (globals.css gets the same :root/.light content, but wrapped in markers)
  const varContent = cssVarBlock
    .replace(/^\/\*.*?\*\/\n\/\*.*?\*\/\n\n/s,'')  // remove 2-line auto-gen header
    .trimEnd();

  const patchedBlock = `${GLOBALS_BEGIN}\n${varContent}\n${GLOBALS_END}`;

  let updated;
  if (original.includes(GLOBALS_BEGIN) && original.includes(GLOBALS_END)) {
    // Replace existing markers
    const beginIdx = original.indexOf(GLOBALS_BEGIN);
    const endIdx = original.indexOf(GLOBALS_END) + GLOBALS_END.length;
    updated = original.slice(0, beginIdx) + patchedBlock + original.slice(endIdx);
  } else {
    // Insert after the last closing brace of the dev-overlay block
    // (before `@layer base`)
    const insertBefore ='\n@layer base {';
    const idx = original.indexOf(insertBefore);
    if (idx === -1) {
      console.warn('  ⚠ Could not find @layer base in globals.css — skipping patch');
      return;
    }
    updated = original.slice(0, idx) +'\n' + patchedBlock +'\n' + original.slice(idx);
  }

  await writeFile(globalsPath, updated,'utf-8');
  console.log(`  ✓ client/src/app/globals.css (patched token vars)`);
}

async function main() {
  console.log('🎨 Building design tokens...\n');

  const tokens = await loadTokens();
  const cssContent = buildCss(tokens);

  const outputs = [
    {
      path: path.join(ROOT,'client/src/generated/tokens.css'),
      content: cssContent,
      label:'CSS (web)',
    },
    {
      path: path.join(ROOT,'client/src/generated/tokens.ts'),
      content: buildTsWeb(tokens),
      label:'TypeScript (web)',
    },
    {
      path: path.join(ROOT,'mobile/src/generated/tokens.ts'),
      content: buildTsMobile(tokens),
      label:'TypeScript (mobile)',
    },
    {
      path: path.join(ROOT,'backend/src/GatherGrove.Application/Generated/DesignTokens.cs'),
      content: buildCSharp(tokens),
      label:'C# (backend)',
    },
  ];

  for (const { path: filepath, content } of outputs) {
    await writeOutput(filepath, content);
  }

  // Patch globals.css with the generated :root/.light vars
  await patchGlobalsCss(cssContent);

  console.log('\n✅ All token files generated successfully.');
}

main().catch((err) => {
  console.error('❌ Token build failed:', err);
  process.exit(1);
});
