/**
 * csharp transform
 *
 * Utilities for generating C# identifiers and source code from design tokens.
 */

/**
 * Convert an array of token path segments to a PascalCase C# identifier.
 * e.g. ['brand', 'primary', '500'] → 'BrandPrimary500'
 *
 * @param {string[]} segments
 * @returns {string}
 */
export function toCSharpIdentifier(segments) {
  return segments
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('');
}

/**
 * Escape a C# string literal value.
 * @param {string} value
 * @returns {string}
 */
export function escapeCSharpString(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Generate the full C# DesignTokens source file content.
 *
 * @param {{ colors: Record<string, string> }} tokens - Flat maps of token name → value
 * @returns {string} Complete C# file content
 */
export function generateCSharpFile(tokens) {
  const colorLines = Object.entries(tokens.colors)
    .map(([name, value]) => {
      const identifier = toCSharpIdentifier(name.split('.'));
      return `        public const string ${identifier} = "${escapeCSharpString(value)}";`;
    })
    .join('\n');

  return `// <auto-generated>
// Generated by shared/design-tokens/build.mjs — do not edit manually.
// Source: shared/design-tokens/colors.json
// To regenerate: npm run tokens:build (from repo root)

namespace GatherGrove.Application.Generated;

/// <summary>
/// Design tokens for consistent styling across GatherGrove.
/// Hex color constants derived from the canonical shared/design-tokens/colors.json.
/// </summary>
public static class DesignTokens
{
    /// <summary>Hex color constants for use in email templates and PDF generation.</summary>
    public static class Colors
    {
${colorLines}
    }
}
`;
}
