// <auto-generated />
using GatherGrove.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GatherGrove.Infrastructure.Migrations
{
    [DbContext(typeof(GatherGroveDbContext))]
    [Migration("20260521010000_AddMarketingLeadEmailSourceUniqueIndex")]
    partial class AddMarketingLeadEmailSourceUniqueIndex
    {
    }
}
