// <auto-generated />
using GatherGrove.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GatherGrove.Infrastructure.Migrations
{
    [DbContext(typeof(GatherGroveDbContext))]
    [Migration("20260531090000_StartPendingGrowTrials")]
    partial class StartPendingGrowTrials
    {
    }
}
